/* Copyright 2017 Philip Polasek. All rights reserved.
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */
package com.sandbox.recipe.service;

import com.sandbox.recipe.domain.LogRecord;
import com.sandbox.recipe.repository.LoggerRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import javax.validation.ConstraintViolationException;
import java.util.Map;

/**
 * --- TODO: Class comments go here ---
 *
 * <b><pre>
 * Copyright 2017 Philip Polasek.
 * All rights reserved.
 * </pre></b>
 *
 * @author ppolasek
 */
@RestController
public class LoggerController {
    @Autowired // This means to get the bean called LoggerRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private LoggerRepository _loggerRepository;

    @CrossOrigin
    @RequestMapping(value = "/logger", method=RequestMethod.POST)
    public void logToDb(@RequestBody LogRecord logRecord) {
//        System.out.println("LoggerController.logToDb() logRecord = " + logRecord.toString());
        try {
            _loggerRepository.save(logRecord);
        } catch (ConstraintViolationException cve) {
            // TODO throw something else to the front end
            System.out.println("LoggerController.logToDb() ConstraintViolationException on the log record." +
                    "\nlogRecord = " + logRecord.toString() +
                    "\ncve=" +
                    cve.getMessage());
            throw new RuntimeException("Unable to save the log record. Check the server for details.");
        }
    }
}
